@startuml
left to right direction

package "Library System" {
  rectangle "User" as user {
   :user1:
  }
  rectangle "Userscases" as usecases {
    (Search Book) as search
    (Back Book) as back
    (Loan Book) as loen
    (Loggin) as userloggin
    (Subscribtion) as (subscribtion)

  }
  user ---> (search)
  user --->(back)
  user ---> (loen)
  user ---> (userloggin)
  user ---> (subscribtion)

  rectangle "CostomerService" as customerservice {
      :customerservice1:
    }

    rectangle "Userscases" as usecases {

      (Edite Book Information) as (editebookinformation)
      (Add Book) as addbook
      (Delete Book) as deletebook


    }

    customerservice ---> (userloggin)
    customerservice ---> (editebookinformation)
    customerservice ---> (addbook)
    customerservice --->  (deletebook)


rectangle "LibraryService" as libraryservice {
    :systemservice:
  }

  rectangle "Userscases" as usecases {

    (Book Manage) as (bookmanage)
    (User Manage) as (usermanage)
     (Registration) as (registration)
     (Library Functionality) as (libraryfunctionality)


  }
  libraryservice ---> (registration)

  libraryservice ---> (bookmanage)
  libraryservice ---> (usermanage)
  libraryservice ---> (libraryfunctionality)

@enduml


