@startuml
actor SystemService
participant "Bibliotheekservice" as BibService

SystemService -> BibService: Select user management function
activate BibService
BibService -> BibService: Check selected function
alt Enroll new user
  BibService -> SystemService: Provide user details
  BibService -> BibService: Add user to database
  BibService -> SystemService: Notify about successful enrollment
else Remove user
  BibService -> SystemService: Select user to remove
  BibService -> SystemService: Confirm removal
  BibService -> BibService: Remove user from database
  BibService -> SystemService: Notify about successful removal
else Block user
  BibService -> SystemService: Select user to block
  BibService -> SystemService: Confirm blocking
  BibService -> BibService: Block user account
  BibService -> SystemService: Notify about successful blocking
else Freeze subscription
  BibService -> SystemService: Select user to freeze subscription
  BibService -> SystemService: Confirm freezing
  BibService -> BibService: Freeze user's subscription
  BibService -> SystemService: Notify about successful freezing
else Reset password
  BibService -> SystemService: Select user to reset password
  BibService -> BibService: Reset user's password
  BibService -> SystemService: Notify about successful password reset
else Invalid selection
  BibService -> SystemService: Notify about invalid selection
end
deactivate BibService
@enduml