@startuml
start
:Gebruiker vraagt om een boek te zoeken;
:Voer de titel van het boek in;
if (Boek gevonden?) then (Ja)
  :Toon boekinformatie;
else (Nee)
  :Toon bericht "Boek niet gevonden";
endif
stop
@enduml

@startuml
Start
:User asks to find a book;
:Enter the title of the book;
if (Book found?) then (Yes)
   :Show book information;
else (No)
   :Show message "Book not found";
endif
Stop
@enduml
