@startuml
start
:Gebruiker vraagt om een boek te lenen;
if (Boek beschikbaar?) then (Ja)
  :Boek lenen;
  :Boek uitlenen aan gebruiker;
  if (Succesvol?) then (Ja)
    :Bericht "Boek succesvol uitgeleend" tonen;
  else (Nee)
    :Bericht "Boek kon niet worden uitgeleend" tonen;
  endif
else (Nee)
  :Bericht "Boek niet beschikbaar" tonen;
endif
stop
@enduml

@startuml
Start
:User asks to borrow a book;
if (Book available?) then (Yes)
   :Borrow a book;
   :Lend book to user;
   if (Successful?) then (Yes)
     :Show "Book successfully checked out" message;
   else (No)
     :Show message "Book could not be borrowed";
   endif
else (No)
   :Show "Book not available" message;
endif
Stop
@enduml