@startuml
start
:Gebruiker klikt op "Inloggen";
:Voer gebruikersnaam en wachtwoord in;
if (Inloggegevens correct?) then (Ja)
  :Gebruiker ingelogd;
  :Toon welkomstbericht;
else (Nee)
  :Toon foutmelding "Onjuiste inloggegevens";
endif
stop
@enduml

@startuml
Start
:User clicks "Login";
:Enter username and password;
if (Login details correct?) then (Yes)
   :User logged in;
   :Show welcome message;
else (No)
   :Show error message "Incorrect login details";
endif
Stop
@enduml




