

@startuml
Start
:User asks to return a book;
:Scan the book to be returned;
if (Book correct?) then (Yes)
   :Return book;
   if (Successful?) then (Yes)
     :Show "Book returned successfully" message;
   else (No)
     :Show "Book could not be returned" message;
   endif
else (No)
   :Show "Invalid book" message;
endif
Stop
@enduml