@startuml
actor Gebruiker
participant "Bibliotheeksysteem" as Bibliotheeksysteem

activate Gebruiker
Gebruiker -> Bibliotheeksysteem: Vraagt om een boek terug te brengen
activate Bibliotheeksysteem

Bibliotheeksysteem -> Bibliotheeksysteem: Scan het terug te brengen boek
alt (Boek correct?) then (Ja)
    Bibliotheeksysteem -> Bibliotheeksysteem: Boek terug inleveren
    alt (Succesvol?) then (Ja)
        Bibliotheeksysteem -> Gebruiker: Bericht "Boek succesvol teruggebracht"
    else (Nee)
        Bibliotheeksysteem -> Gebruiker: Bericht "Boek kon niet worden teruggebracht"
    end
else (Nee)
    Bibliotheeksysteem -> Gebruiker: Bericht "Ongeldig boek"
end

deactivate Bibliotheeksysteem
deactivate Gebruiker
@enduml

@startuml
actor User
participant "LibrarySystem" as LibrarySystem

activate User
User -> LibrarySystem: Requests to return a book
activate Librarysystem

Librarysystem -> Librarysystem: Scan the book to be returned
alt (Book correct?) then (Yes)
     Librarysystem -> Librarysystem: Return book
     alt (Successful?) then (Yes)
         LibrarySystem -> User: "Book Returned Successfully" Message
     else (No)
         LibrarySystem -> User: "Book could not be returned" message
     end
else (No)
     LibrarySystem -> User: "Invalid Book" Message
end

deactivate Librarysystem
deactivate User
@enduml
