@startuml
actor Gebruiker
participant "Bibliotheeksysteem" as Bibliotheeksysteem

activate Gebruiker
Gebruiker -> Bibliotheeksysteem: Vraagt om een boek te lenen
activate Bibliotheeksysteem

Bibliotheeksysteem -> Bibliotheeksysteem: Controleert of boek beschikbaar is
alt Boek beschikbaar?
    Bibliotheeksysteem -> Bibliotheeksysteem: Boek lenen
    Bibliotheeksysteem -> Bibliotheeksysteem: Boek uitlenen aan gebruiker
    alt (Succesvol?)
        Bibliotheeksysteem -> Gebruiker: Bericht "Boek succesvol uitgeleend"
    else
        Bibliotheeksysteem -> Gebruiker: Bericht "Boek kon niet worden uitgeleend"
    end
else
    Bibliotheeksysteem -> Gebruiker: Bericht "Boek niet beschikbaar"
end

deactivate Bibliotheeksysteem
deactivate Gebruiker
@enduml

@startuml
actor User
participant "LibrarySystem" as LibrarySystem

activate User
User -> LibrarySystem: Asks to borrow a book
activate Librarysystem

LibrarySystem -> LibrarySystem: Checks if book is available
alt Book available? (yes)
     Librarysystem -> Librarysystem: Borrow a book
     Librarysystem -> Librarysystem: Loan book to user
     alt (Successful?)
         Librarysystem -> User: Message "Book checked out successfully"
     else (no)
         Librarysystem -> User: Message "Book could not be checked out"
     end
else (no)
     LibrarySystem -> User: "Book Not Available" Message
end

deactivate Librarysystem
deactivate User
@enduml
