@startuml
actor Gebruiker
participant "Bibliotheeksysteem" as Bibliotheeksysteem

activate Gebruiker
Gebruiker -> Bibliotheeksysteem: Vraagt om een boek te zoeken
activate Bibliotheeksysteem

Bibliotheeksysteem -> Bibliotheeksysteem: Voer de titel van het boek in
alt (Boek gevonden?) then (Ja)
    Bibliotheeksysteem -> Gebruiker: Toon boekinformatie
else (Nee)
    Bibliotheeksysteem -> Gebruiker: Toon bericht "Boek niet gevonden"
end

deactivate Bibliotheeksysteem
deactivate Gebruiker
@enduml


@startuml
actor User
participant "LibrarySystem" as LibrarySystem

activate User
User -> LibrarySystem: Asks to find a book
activate Librarysystem

LibrarySystem -> LibrarySystem: Enter the title of the book
alt (Book found?) then (Yes)
     LibrarySystem -> User: Show book information
else (No)
     Librarysystem -> User: Show message "Book not found"
end

deactivate Librarysystem
deactivate User
@enduml