@startuml
start
:User selects book management function;
if (Selected function is Move book to another category?) then (yes)
  :User selects book to move;
  :User selects target category;
  :Move book to target category;
  :Notify user about successful move;
elseif (Selected function is Restore book?) then (yes)
  :User selects book to restore;
  :Check book condition;
  if (Book condition is restoreable?) then (yes)
    :Restore book;
    :Notify user about successful restoration;
  else (no)
    :Notify user about inability to restore book;
  endif
elseif (Selected function is Add book information?) then (yes)
  :User selects book to add information to;
  :User provides additional information;
  :Update book information in database;
  :Notify user about successful update;
elseif (Selected function is Mark book?) then (yes)
  :User selects book to mark;
  :Mark book with library stamp;
  :Notify user about successful marking;
elseif (Selected function is Calculate book popularity?) then (yes)
  :Calculate popularity of each book;
  :Display popularity ranking of books;
else
  :Notify user about invalid selection;
endif
stop
@enduml