
@startuml
Start
:Administrator clicks "Login";
:Enter username and password;
if (Login details correct?) then (Yes)
   :Administrator logged in;
   :Show welcome message;
else (No)
   :Show error message "Incorrect login details";
endif
Stop
@enduml




























