


@startuml
actor User
participant "LibrarySystem" as LibrarySystem

activate User
User -> LibrarySystem: Asks to find a book
activate Librarysystem

LibrarySystem -> LibrarySystem: Enter the title of the book
alt (Book found?) then (Yes)
     LibrarySystem -> User: Show book information
else (No)
     Librarysystem -> User: Show message "Book not found"
end

deactivate Librarysystem
deactivate User
@enduml