@startuml
left to right direction

package "Bibliotheeksysteem" {
  rectangle "Gebruiker" as gebruiker {
    :user:
  }
  rectangle "Gebruikscases" as usecases {
    (Boek Zoeken) as zoek
    (Boek terugkrijgen) as terugkrijgen
    (Boek Lening) as lening
    (Inloggen) as gebruikerInloggen
    (Abbonement) as (abbonment)

  }
  gebruiker ---> (zoek)
  gebruiker --->(terugkrijgen)
  gebruiker ---> (lening)
  gebruiker ---> (gebruikerInloggen)
  gebruiker ---> (abbonment)

  rectangle "Klantenservice" as klantenservice {
      :klantenservice1:
    }

    rectangle "Gebruikscases" as usecases {

      (Boek Informatie Bewerken) as boekinformatiebewerken
      (Boek Toevoegen) as toevoegen
      (Boek verdewijnen) as verdewijnen

    }

    klantenservice ---> (gebruikerInloggen)
    klantenservice ---> (boekinformatiebewerken)
    klantenservice ---> (toevoegen)
    klantenservice --->  (verdewijnen)


rectangle "Bibliotheekservice" as bibliotheekservice {
    :service:
  }

  rectangle "Gebruikscases" as usecases {
    (Boek beheren) as (boekbeheren)
    (Gebruikers Beheren) as gebruikerbeheren
     (Registratie) as (registratie)
     (Bibliotheek Functionaliteit) as functionaliteit

  }
  bibliotheekservice ---> (registratie)

  bibliotheekservice ---> (boekbeheren)
  bibliotheekservice ---> (gebruikerbeheren)
  bibliotheekservice ---> (functionaliteit)

@enduml
@startuml
left to right direction

package "Bibliotheeksysteem" {
  rectangle "Gebruiker" as gebruiker {
    :user:
  }

  rectangle "Gebruikscases" as usecases {
    (Boek Zoeken) as zoek
    (Boek terugkrijgen) as terugkrijgen
    (Boek Lening) as lening
    (Inloggen) as gebruikerInloggen
    (Abbonement) as (abbonment)

  }

  gebruiker ---> (zoek)
  gebruiker --->(terugkrijgen)
  gebruiker ---> (lening)
  gebruiker ---> (gebruikerInloggen)
  gebruiker ---> (abbonment)




  rectangle "Klantenservice" as klantenservice {
      :klantenservice1:
    }

    rectangle "Gebruikscases" as usecases {

      (Boek Informatie Bewerken) as boekinformatiebewerken
      (Boek Toevoegen) as toevoegen
      (Boek verdewijnen) as verdewijnen


    }

    klantenservice ---> (gebruikerInloggen)
    klantenservice ---> (boekinformatiebewerken)
    klantenservice ---> (toevoegen)
    klantenservice --->  (verdewijnen)


rectangle "Bibliotheekservice" as bibliotheekservice {
    :service:
  }

  rectangle "Gebruikscases" as usecases {

    (Boek beheren) as (boekbeheren)
    (Gebruikers Beheren) as gebruikerbeheren
     (Registratie) as (registratie)
     (Bibliotheek Functionaliteit) as functionaliteit

  }

  bibliotheekservice ---> (registratie)

  bibliotheekservice ---> (boekbeheren)
  bibliotheekservice ---> (gebruikerbeheren)
  bibliotheekservice ---> (functionaliteit)


@enduml